services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: path-handler-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: path-handler-db
    environment:
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=veryveryveryStrongPasswordHeh
      - POSTGRES_DB=pathhandler
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  caddy_data:
  db_data:
